// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/dem.proto

package dempb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type File struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileName             string   `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileType             string   `protobuf:"bytes,4,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	EncFileId            string   `protobuf:"bytes,5,opt,name=enc_file_id,json=encFileId,proto3" json:"enc_file_id,omitempty"`
	CreateDate           string   `protobuf:"bytes,6,opt,name=create_date,json=createDate,proto3" json:"create_date,omitempty"`
	OpenFileDate         string   `protobuf:"bytes,7,opt,name=open_file_date,json=openFileDate,proto3" json:"open_file_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea4ac1dbb2a881ac, []int{0}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *File) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *File) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *File) GetFileType() string {
	if m != nil {
		return m.FileType
	}
	return ""
}

func (m *File) GetEncFileId() string {
	if m != nil {
		return m.EncFileId
	}
	return ""
}

func (m *File) GetCreateDate() string {
	if m != nil {
		return m.CreateDate
	}
	return ""
}

func (m *File) GetOpenFileDate() string {
	if m != nil {
		return m.OpenFileDate
	}
	return ""
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserNameSurname      string   `protobuf:"bytes,2,opt,name=user_name_surname,json=userNameSurname,proto3" json:"user_name_surname,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Region               string   `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	Language             string   `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	CreateDate           string   `protobuf:"bytes,7,opt,name=create_date,json=createDate,proto3" json:"create_date,omitempty"`
	SharedFileCount      string   `protobuf:"bytes,8,opt,name=shared_file_count,json=sharedFileCount,proto3" json:"shared_file_count,omitempty"`
	EmptySpace           string   `protobuf:"bytes,9,opt,name=empty_space,json=emptySpace,proto3" json:"empty_space,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea4ac1dbb2a881ac, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetUserNameSurname() string {
	if m != nil {
		return m.UserNameSurname
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *User) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *User) GetCreateDate() string {
	if m != nil {
		return m.CreateDate
	}
	return ""
}

func (m *User) GetSharedFileCount() string {
	if m != nil {
		return m.SharedFileCount
	}
	return ""
}

func (m *User) GetEmptySpace() string {
	if m != nil {
		return m.EmptySpace
	}
	return ""
}

type RegisterUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserRequest) Reset()         { *m = RegisterUserRequest{} }
func (m *RegisterUserRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRequest) ProtoMessage()    {}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea4ac1dbb2a881ac, []int{2}
}

func (m *RegisterUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRequest.Unmarshal(m, b)
}
func (m *RegisterUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRequest.Marshal(b, m, deterministic)
}
func (m *RegisterUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRequest.Merge(m, src)
}
func (m *RegisterUserRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRequest.Size(m)
}
func (m *RegisterUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRequest proto.InternalMessageInfo

func (m *RegisterUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type RegisterUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserResponse) Reset()         { *m = RegisterUserResponse{} }
func (m *RegisterUserResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterUserResponse) ProtoMessage()    {}
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea4ac1dbb2a881ac, []int{3}
}

func (m *RegisterUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserResponse.Unmarshal(m, b)
}
func (m *RegisterUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserResponse.Marshal(b, m, deterministic)
}
func (m *RegisterUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserResponse.Merge(m, src)
}
func (m *RegisterUserResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterUserResponse.Size(m)
}
func (m *RegisterUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserResponse proto.InternalMessageInfo

func (m *RegisterUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type LoginUserRequest struct {
	UserId               *User    `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUserRequest) Reset()         { *m = LoginUserRequest{} }
func (m *LoginUserRequest) String() string { return proto.CompactTextString(m) }
func (*LoginUserRequest) ProtoMessage()    {}
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea4ac1dbb2a881ac, []int{4}
}

func (m *LoginUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserRequest.Unmarshal(m, b)
}
func (m *LoginUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserRequest.Marshal(b, m, deterministic)
}
func (m *LoginUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserRequest.Merge(m, src)
}
func (m *LoginUserRequest) XXX_Size() int {
	return xxx_messageInfo_LoginUserRequest.Size(m)
}
func (m *LoginUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserRequest proto.InternalMessageInfo

func (m *LoginUserRequest) GetUserId() *User {
	if m != nil {
		return m.UserId
	}
	return nil
}

type LoginUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUserResponse) Reset()         { *m = LoginUserResponse{} }
func (m *LoginUserResponse) String() string { return proto.CompactTextString(m) }
func (*LoginUserResponse) ProtoMessage()    {}
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea4ac1dbb2a881ac, []int{5}
}

func (m *LoginUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserResponse.Unmarshal(m, b)
}
func (m *LoginUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserResponse.Marshal(b, m, deterministic)
}
func (m *LoginUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserResponse.Merge(m, src)
}
func (m *LoginUserResponse) XXX_Size() int {
	return xxx_messageInfo_LoginUserResponse.Size(m)
}
func (m *LoginUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserResponse proto.InternalMessageInfo

func (m *LoginUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea4ac1dbb2a881ac, []int{6}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea4ac1dbb2a881ac, []int{7}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteUserRequest struct {
	UserId               *User    `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea4ac1dbb2a881ac, []int{8}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetUserId() *User {
	if m != nil {
		return m.UserId
	}
	return nil
}

type DeleteUserResponse struct {
	UserId               *User    `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea4ac1dbb2a881ac, []int{9}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

func (m *DeleteUserResponse) GetUserId() *User {
	if m != nil {
		return m.UserId
	}
	return nil
}

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea4ac1dbb2a881ac, []int{10}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea4ac1dbb2a881ac, []int{11}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*File)(nil), "dem.File")
	proto.RegisterType((*User)(nil), "dem.User")
	proto.RegisterType((*RegisterUserRequest)(nil), "dem.RegisterUserRequest")
	proto.RegisterType((*RegisterUserResponse)(nil), "dem.RegisterUserResponse")
	proto.RegisterType((*LoginUserRequest)(nil), "dem.LoginUserRequest")
	proto.RegisterType((*LoginUserResponse)(nil), "dem.LoginUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "dem.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "dem.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "dem.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "dem.DeleteUserResponse")
	proto.RegisterType((*HelloRequest)(nil), "dem.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "dem.HelloResponse")
}

func init() { proto.RegisterFile("proto/dem.proto", fileDescriptor_ea4ac1dbb2a881ac) }

var fileDescriptor_ea4ac1dbb2a881ac = []byte{
	// 560 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0xd3, 0x5c,
	0x10, 0x55, 0xd2, 0x34, 0x89, 0x27, 0xf9, 0xda, 0xcf, 0x17, 0x68, 0x4d, 0x10, 0x3f, 0xb2, 0x58,
	0x40, 0x17, 0x45, 0xa4, 0xfc, 0x09, 0x89, 0x0d, 0x8d, 0x10, 0x95, 0x10, 0x8b, 0x84, 0x6e, 0xd8,
	0x58, 0xb7, 0xbe, 0x43, 0xb0, 0xe4, 0x3f, 0x7c, 0x1d, 0x50, 0xde, 0x85, 0x67, 0xe1, 0x19, 0x78,
	0x24, 0x34, 0x73, 0xaf, 0x13, 0x37, 0x8e, 0x44, 0xd8, 0x79, 0xce, 0x99, 0x33, 0x73, 0xcf, 0xcc,
	0xc8, 0x70, 0x98, 0x17, 0x59, 0x99, 0x3d, 0x51, 0x98, 0x9c, 0xf2, 0x97, 0xd8, 0x53, 0x98, 0xf8,
	0xbf, 0x5b, 0xd0, 0x79, 0x17, 0xc5, 0x28, 0x0e, 0xa0, 0x1d, 0x29, 0xaf, 0xf5, 0xa0, 0xf5, 0xc8,
	0x99, 0xb6, 0x23, 0x25, 0x8e, 0xa1, 0xb7, 0xd0, 0x58, 0x04, 0x91, 0xf2, 0xda, 0x0c, 0x76, 0x29,
	0xbc, 0x50, 0xe2, 0x0e, 0x38, 0x5f, 0xa2, 0x18, 0x83, 0x54, 0x26, 0xe8, 0xed, 0x31, 0xd5, 0x27,
	0xe0, 0xa3, 0x4c, 0x70, 0x45, 0x96, 0xcb, 0x1c, 0xbd, 0xce, 0x9a, 0xfc, 0xb4, 0xcc, 0x51, 0xdc,
	0x83, 0x01, 0xa6, 0x61, 0xc0, 0x09, 0x91, 0xf2, 0xf6, 0x99, 0x76, 0x30, 0x0d, 0xe9, 0x01, 0x17,
	0x4a, 0xdc, 0x87, 0x41, 0x58, 0xa0, 0x2c, 0x31, 0x50, 0xb2, 0x44, 0xaf, 0xcb, 0x3c, 0x18, 0x68,
	0x22, 0x4b, 0x14, 0x0f, 0xe1, 0x20, 0xcb, 0x31, 0x35, 0x15, 0x38, 0xa7, 0xc7, 0x39, 0x43, 0x42,
	0xa9, 0x08, 0x65, 0xf9, 0x3f, 0xdb, 0xd0, 0xb9, 0xd4, 0x58, 0x34, 0x2c, 0x9d, 0x80, 0xcb, 0x96,
	0xe8, 0xe5, 0x81, 0x5e, 0x14, 0xec, 0xc0, 0x98, 0x3b, 0x24, 0x82, 0x1c, 0xcc, 0x0c, 0x2c, 0x46,
	0xd0, 0x27, 0xa8, 0x6e, 0xb2, 0x8a, 0x89, 0xcb, 0xa5, 0xd6, 0x3f, 0xb2, 0x42, 0x55, 0x1e, 0xab,
	0x58, 0x1c, 0x41, 0xb7, 0xc0, 0x79, 0x94, 0xa5, 0xd6, 0x9e, 0x8d, 0x48, 0x13, 0xcb, 0x74, 0xbe,
	0x90, 0xf3, 0xca, 0xd8, 0x2a, 0xde, 0xf4, 0xdd, 0x6b, 0xf8, 0x3e, 0x01, 0x57, 0x7f, 0x95, 0x05,
	0x2a, 0xe3, 0x3c, 0xcc, 0x16, 0x69, 0xe9, 0xf5, 0xcd, 0xc3, 0x0d, 0x41, 0xe6, 0xcf, 0x09, 0xa6,
	0x62, 0x98, 0xe4, 0xe5, 0x32, 0xd0, 0xb9, 0x0c, 0xd1, 0x73, 0x4c, 0x31, 0x86, 0x66, 0x84, 0xf8,
	0xcf, 0xe0, 0xc6, 0x14, 0xe7, 0x91, 0x2e, 0xb1, 0xa0, 0x29, 0x4d, 0xf1, 0xdb, 0x02, 0x75, 0x29,
	0xee, 0x42, 0x87, 0x0c, 0xf2, 0xb8, 0x06, 0x63, 0xe7, 0x94, 0xee, 0x84, 0x79, 0x86, 0xfd, 0xe7,
	0x70, 0xf3, 0xba, 0x4a, 0xe7, 0x59, 0xaa, 0xf1, 0x6f, 0xb2, 0x17, 0xf0, 0xff, 0x87, 0x6c, 0x1e,
	0xa5, 0xf5, 0x4e, 0xfe, 0xfa, 0xb2, 0x1a, 0x2a, 0x7b, 0x64, 0xfe, 0x18, 0xdc, 0x9a, 0x6e, 0xb7,
	0x5e, 0x63, 0x70, 0x2f, 0x73, 0x9a, 0xe0, 0x3f, 0xd8, 0x3a, 0x03, 0x51, 0xd7, 0xec, 0xd6, 0xe8,
	0x25, 0xb8, 0x13, 0x8c, 0xf1, 0x7a, 0xa3, 0x5d, 0x5c, 0xbd, 0x02, 0x51, 0x17, 0xda, 0x6e, 0xbb,
	0x28, 0x7d, 0x18, 0xbe, 0xc7, 0x38, 0xce, 0xaa, 0x6e, 0x02, 0x3a, 0x7c, 0x9a, 0xe6, 0xb8, 0xf9,
	0xdb, 0x7f, 0x0c, 0xff, 0xd9, 0x1c, 0x5b, 0xd8, 0x83, 0x5e, 0x82, 0x5a, 0xd3, 0xc9, 0x99, 0xbc,
	0x2a, 0x1c, 0xff, 0x6a, 0x03, 0x4c, 0x30, 0x99, 0x61, 0xf1, 0x3d, 0x0a, 0x51, 0x9c, 0xc3, 0xb0,
	0xbe, 0x5c, 0xe1, 0xf1, 0x03, 0xb6, 0x5c, 0xc9, 0xe8, 0xf6, 0x16, 0xc6, 0x76, 0x7b, 0x0d, 0xce,
	0x6a, 0x65, 0xe2, 0x16, 0xe7, 0x6d, 0xae, 0x7e, 0x74, 0xb4, 0x09, 0x5b, 0xed, 0x1b, 0x80, 0xf5,
	0x1a, 0x84, 0xc9, 0x6a, 0xec, 0x72, 0x74, 0xdc, 0xc0, 0xd7, 0xf2, 0xf5, 0x5c, 0xad, 0xbc, 0xb1,
	0x21, 0x2b, 0xdf, 0xb2, 0x80, 0xa7, 0xd0, 0x9f, 0xc9, 0x25, 0xcf, 0x4e, 0xb8, 0x9c, 0x54, 0x9f,
	0xf5, 0x48, 0xd4, 0x21, 0x23, 0x79, 0xdb, 0xfb, 0xbc, 0xaf, 0x30, 0xc9, 0xaf, 0xae, 0xba, 0xfc,
	0x2f, 0x3d, 0xfb, 0x13, 0x00, 0x00, 0xff, 0xff, 0xee, 0x85, 0xb3, 0x1d, 0x5e, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DemServiceClient is the client API for DemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DemServiceClient interface {
	RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
	// return NOT_FOUND if not found
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	// return NOT_FOUND if not found
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type demServiceClient struct {
	cc *grpc.ClientConn
}

func NewDemServiceClient(cc *grpc.ClientConn) DemServiceClient {
	return &demServiceClient{cc}
}

func (c *demServiceClient) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	out := new(RegisterUserResponse)
	err := c.cc.Invoke(ctx, "/dem.DemService/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demServiceClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, "/dem.DemService/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/dem.DemService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, "/dem.DemService/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/dem.DemService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DemServiceServer is the server API for DemService service.
type DemServiceServer interface {
	RegisterUser(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error)
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	// return NOT_FOUND if not found
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	// return NOT_FOUND if not found
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
}

func RegisterDemServiceServer(s *grpc.Server, srv DemServiceServer) {
	s.RegisterService(&_DemService_serviceDesc, srv)
}

func _DemService_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemServiceServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dem.DemService/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemServiceServer).RegisterUser(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DemService_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemServiceServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dem.DemService/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemServiceServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DemService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dem.DemService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DemService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dem.DemService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DemService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dem.DemService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DemService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dem.DemService",
	HandlerType: (*DemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _DemService_RegisterUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _DemService_LoginUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _DemService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _DemService_DeleteUser_Handler,
		},
		{
			MethodName: "SayHello",
			Handler:    _DemService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dem.proto",
}
